version: '3.9'
services:
  db:
    image: postgres:13.4
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./test-env

  redis:
    image: redis:latest
    restart: always

  backend:
    build:
      context: ../backend/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./test-env

  migrations:
    build:
      context: ../backend/
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
    - db
    - backend

  nginx:
    image: nginx:1.21.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  static_value:
  media_value:
  postgres: