# Generated by Django 4.2.1 on 2023-07-08 15:29

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите наименование путешествия', max_length=200, unique=True, verbose_name='Наименование путешествия')),
                ('start_date', models.DateField(help_text='Укажите дату начала путешествия', verbose_name='Дата начала путешествия')),
                ('end_date', models.DateField(help_text='Укажите дату окончания путешествия', verbose_name='Дата окончания путешествия')),
                ('image', models.ImageField(default=None, null=True, upload_to='travel_diary/images/')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=255, verbose_name='Название события')),
                ('category', models.CharField(help_text='Выберите категорию', max_length=50, verbose_name='Категория события')),
                ('address', models.CharField(help_text='Укажите адрес', max_length=255, null=True, verbose_name='Адрес')),
                ('date', models.DateField(db_index=True, help_text='Введите дату', verbose_name='Дата')),
                ('time', models.TimeField(db_index=True, help_text='Введите время', verbose_name='Время')),
                ('description', models.CharField(blank=True, help_text='Введите описание', max_length=255, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена')),
                ('media', models.FileField(blank=True, help_text='Загрузите файл', null=True, upload_to='files/', validators=[api.validators.validate_file_extension], verbose_name='Файл')),
                ('origin', models.CharField(help_text='Введите пункт отправления', max_length=50, null=True, verbose_name='Откуда')),
                ('destination', models.CharField(help_text='Введите пункт назначения', max_length=50, null=True, verbose_name='Куда')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='travel_diary.travel')),
            ],
            options={
                'verbose_name': 'Карточка активностей',
                'verbose_name_plural': 'Карточки активностей',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
