# Generated by Django 4.2.1 on 2023-07-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену', max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='travel_diary/images/'),
        ),
    ]
