# Generated by Django 4.2.1 on 2023-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0002_remove_activity_media_alter_activity_price_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Введите цену', max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(blank=True, help_text='Введите время', null=True, verbose_name='Время'),
        ),
    ]
