# Generated by Django 4.2.1 on 2023-07-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='traveller',
            new_name='traveler',
        ),
    ]
