# Generated by Django 4.2.1 on 2023-07-23 10:13

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0002_alter_activity_price_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='media',
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.IntegerField(blank=True, help_text='Введите цену', null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(help_text='Загрузите файл', upload_to='files/', validators=[api.validators.validate_file_extension], verbose_name='Файл')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='travel_diary.activity', verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Медиа файл',
                'verbose_name_plural': 'Медиа файлы',
                'ordering': ('activity',),
            },
        ),
    ]
