# Generated by Django 4.2.1 on 2023-07-21 18:27

import api.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel_diary', '0003_rename_traveller_travel_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='media',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='image',
        ),
        migrations.AddField(
            model_name='travel',
            name='description',
            field=models.CharField(blank=True, help_text='Укажите описание путешествия', max_length=2000, null=True, verbose_name='Описание путешествия'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='travel_diary.travel'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='name',
            field=models.CharField(help_text='Укажите название путешествия', max_length=100, unique=True, verbose_name='Название путешествия'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(help_text='Загрузите файл', upload_to='files/', validators=[api.validators.validate_file_extension], verbose_name='Файл')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='travel_diary.activity', verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Медиа файл',
                'verbose_name_plural': 'Медиа файлы',
                'ordering': ('activity',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_diary/images/')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel_diary.travel', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('travel',),
            },
        ),
    ]
