# Generated by Django 4.2.1 on 2023-09-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0003_alter_activity_price_alter_activity_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date', models.OrderBy(models.F('time'), descending=True, nulls_last=True)], 'verbose_name': 'Карточка активностей', 'verbose_name_plural': 'Карточки активностей'},
        ),
    ]
