# Generated by Django 4.2.1 on 2023-10-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_diary', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='filename',
            field=models.CharField(default='noname', max_length=255, verbose_name='Имя файла'),
            preserve_default=False,
        ),
    ]
